spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show sql: true
        format sql: true
jwt:
  secret: secret
